### ISSUE TITLE
Services should not consume exceptions

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#12]
Currently, many service method implementations catch and consume exceptions.  This makes it hard to debug errors!

Instead, exceptions should be bubbled up to the caller or converted to ConstraintViolations and thrown or returned to the caller.  This will allow the REST resources to return useful errors.

LocationHierarchyService is one implementation that consumes exceptions:
https://github.com/USM-RCG/openhds-server/blob/master/controller/src/main/java/org/openhds/controller/service/impl/LocationHierarchyServiceImpl.java#L448

**Comment by andrew-d-taylor** [comment]
Improved exception handling is one of the core concerns of W. Lienhardt's master's project, beginning in the summer of 2015. Closing this generic issue in light of that.
