### ISSUE TITLE
WebserviceResult handy method for general exceptions

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#13]
Currently WebserviceResultHelper has a handy method for creating a WebserviceResult that reflects a domain constraint violation.

Add a similar method to reflect general server errors.  This should return an INTERNAL_SERVER_ERROR status.

**Comment by andrew-d-taylor** [comment]
REST resource exception handling is a component of B. Heasley's thesis work starting summer 2015.
