### ISSUE TITLE
Refactoring for all services

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#16]
Refactor the service around the EntityService layer super type.

The service should throw exceptions and constraint violations to the caller, and not attempt to consume them or convert them to another type. 

The service should attempt to return expected data, or else thrown an exception.  It should not "report" errors by returning null or modifying its inputs.

The service should expose a utility method for creating any relevant domain objects.  The utility method signature should include all fields that are required in order to successfully create and persist the objects (for example, all fields that are marked "not null").

**Comment by andrew-d-taylor** [comment]
Service layer re-factoring is a component of W. Lienhardt's master's project starting summer 2015.
