### ISSUE TITLE
Web REST resources

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#17]
Revisit the web REST resource and re-implement in the style of recent changes by Russell Gillen: 23d21f5

Add support for four REST verbs: GET, POST, PUT, and DELETE.

Add support for XML and JSON inputs and outputs. XML and JSON outputs should be based on the new WebserviceResult, with useful status codes, messages, and data payload.

Add integration tests to verify that correct CRUD operations from the resource methods. Integration tests should use the re-factored services (Issue #16) to verify CRUD results.

**Comment by andrew-d-taylor** [comment]
A re-factoring of the REST API is a component of B. Heasley's thesis work starting summer 2015.
