### ISSUE TITLE
Review dao daoApplicationContext.xml

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#40]
daoApplicationContext declares makes many class-specific declarations.  Can we simplify the dao configuration with package scanning?

Specifically:
 * The sessionFactory bean declares an explicit list of annotatedClasses.  Can we replaces the list of classes with a list of packages to scan?
 * There are many explicit dao bean declarations, like deathDao and fieldWorkerDao.  Is the application using all of these?  Can we remove many of these declarations and use the genericDao instead?

**Comment by andrew-d-taylor** [comment]
Reconsidering the several statically-defined application contexts is a component of B. Heasley's thesis work starting summer 2015.
