### ISSUE TITLE
Implement a generic REST resource supertype?

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-server#44]
Creating a separate REST resources for each service might require a lot of code duplication, especially if we want to support multiple HTTP verbs, XML, and JSON, for each resource.

Example 11.3 of Spring in Practice suggests that we could factor out a lot of common code into a resource supertype:
https://github.com/springinpractice/sip11/blob/master/service/src/main/java/com/springinpractice/ch11/web/controller/AbstractCrudController.java

This should conveniently support XML and JSON, as of Spring 3.2:
https://jira.spring.io/browse/SPR-9153

**Comment by andrew-d-taylor** [comment]
A re-factoring of the REST resources is a component of B. Heasley's thesis work starting summer 2015.
