### ISSUE TITLE
Implement SSL on the Server

### ISSUE THREAD

**Issue by nathan-wolfe-lienhardt** [USM-RCG/openhds-server#78]
Currently the server does not have an [SSL](http://en.wikipedia.org/wiki/Transport_Layer_Security) certificate.

The field team will have to be asked for information relevant for a CSR which will then be sent to a reputable Certificate Authority.

Some options are:
+ Symantec
+ Comodo SSL
+ GoDaddy
+ GlobalSign

**Comment by andrew-d-taylor** [comment]
SSL is now in place as of the 16January2015 release
